# Zakum Crates Configuration
settings:
  storage:
    table-prefix: "orbis_crates_"
  
  gui:
    title: "Global Crates"
    rows: 3
    fill-item: GRAY_STAINED_GLASS_PANE

crates:
  vote:
    name: "&a&lVote Crate"
    type: ROULETTE
    preview: true
    block: ENDER_CHEST
    key:
      material: TRIPWIRE_HOOK
      name: "&aVote Key"
      lore:
        - "&7Use this at the crate area"
        - "&7to win rewards!"
      glow: true
  
  rare:
    name: "&6&lRare Crate"
    type: CSGO
    preview: true
    block: TRAPPED_CHEST
    key:
      material: BLAZE_ROD
      name: "&6Rare Key"
      glow: true
